print('\nВведите любую строку, кроме пустого значения, например "Топинамбур" \n')
example=input()
print('\n ')
print(example[0])
print(example[-1])
print(example[len(example)//2::])
print(example[::-1])
print(example[1::2])
print('\nПрактическое задание №1 "Строки и интексация строк" выполнено.')